### ISSUE TITLE
Need to close this repository?

### ISSUE THREAD

**Issue by sojharo** [Cloudkibo/KibosupportMarketing#1]
We have combined both marketing websites (cloudkibo and kibosupport) under following repository

https://github.com/Cloudkibo/CloudkiboMarketing

So, we won't be needing this one and all the updates to any of marketing website will be done in above repository. We can close or delete this repository.

**Comment by jekram** [comment]
@sojharo 

I wanted to reconfirm if I should delete this repo.

So both cloudkibo & kibosupport are in 

 https://github.com/Cloudkibo/CloudkiboMarketing

**Comment by sojharo** [comment]
We had some issues in combining them on one server. Therefore, this is being used as separate server.

**Comment by jekram** [comment]
I am not talking about server but Githib repo?

**Comment by sojharo** [comment]
yes we also use it.
